define all_for_this_update_phrase = "Thats all for this update1"
define no_tips_for_now = "No tips for now"

define aphrodite_phase1 = all_for_this_update_phrase
# ......
define linda_phase1 = all_for_this_update_phrase
# ......
define monica_phase1 = "phase 1"
define monica_phase2 = all_for_this_update_phrase
# ......
define sarah_phase1 = all_for_this_update_phrase
# ......
define ashley_phase1 = all_for_this_update_phrase
# ......
define ayame_phase1 = all_for_this_update_phrase
# ......
define kogame_phase1 = all_for_this_update_phrase
# ......
define debbie_phase1 = no_tips_for_now
# ......
define anita_phase1 = all_for_this_update_phrase
# ......
define makoto_phase1 = all_for_this_update_phrase
# ......
define nina_phase1 = all_for_this_update_phrase
# ......
define shino_phase1 = all_for_this_update_phrase
# ......
define ung_phase1 = all_for_this_update_phrase
# ......
define lilith_phase1 = all_for_this_update_phrase
# ......
