define all_for_this_update_phrase = "Thats all for this update"
define no_tips_for_now = "No tips for now"

define aphrodite_phase1 = all_for_this_update_phrase
# ......
define linda_phase1 = no_tips_for_now
define linda_phase2 = "Give the teddy bear to her."
define linda_phase3 = all_for_this_update_phrase
# ......
define monica_phase1 = "phase 1"
define monica_phase2 = no_tips_for_now
define monica_phase3 = "Talk about her husband (kitchen morning)"
define monica_phase4 = "Find a way to Enter Ashley´s room"
# ......
define sarah_phase1 = all_for_this_update_phrase
# ......
define ashley_phase1 = no_tips_for_now
define ashley_phase2 = "Bring her the milk wipe away your debt."
# ......
define ayame_phase1 = all_for_this_update_phrase
# ......
define kogame_phase1 = all_for_this_update_phrase
# ......
define debbie_phase1 = no_tips_for_now
define debbie_phase2 = "Buy the teddybear on the guild store."
define debbie_phase3 = no_tips_for_now
define debbie_phase4 = "Ask her about the missing milk."
define debbie_phase5 = "Sell some milk to her."
# ......
define anita_phase1 = all_for_this_update_phrase
# ......
define makoto_phase1 = all_for_this_update_phrase
# ......
define nina_phase1 = all_for_this_update_phrase
# ......
define shino_phase1 = all_for_this_update_phrase
# ......
define ung_phase1 = all_for_this_update_phrase
# ......
define lilith_phase1 = all_for_this_update_phrase
# ......

